In [ ]:
import numpy as np
import pandas as pd


In [ ]:
data=[(2, 1), (3, 4), (5, 0), (7, 6), (9, 2)]


In [ ]:
import pandas as pd


data = [(2,1),(3,4),(5,0),(7,6),(9,2)]

data_frame = pd.DataFrame(data)

data_frame.columns = ['Column_1', 'Column_2']


print(data_frame)
column_means = data_frame.mean()
column_std = data_frame.std()

print("\nMean for each column:")
print(column_means)

print("\nStandard deviation for each column:")
print(column_std)

deviations_matrix = data_frame.subtract(column_means)
print(deviations_matrix)


   Column_1  Column_2
0         2         1
1         3         4
2         5         0
3         7         6
4         9         2

Mean for each column:
Column_1    5.2
Column_2    2.6
dtype: float64

Standard deviation for each column:
Column_1    2.863564
Column_2    2.408319
dtype: float64
   Column_1  Column_2
0      -3.2      -1.6
1      -2.2       1.4
2      -0.2      -2.6
3       1.8       3.4
4       3.8      -0.6


In [ ]:
cov_matrix = np.cov(data, rowvar=False)

print("Covariance Matrix:")
print(cov_matrix)

Covariance Matrix:
[[8.2 1.6]
 [1.6 5.8]]


In [ ]:
eigenvalues,eigenvector=np.linalg.eig(cov_matrix)
print("Eigen values\n")
print(eigenvalues)
print("Eigen vectors\n")
print(eigenvector)


Eigen values

[9. 5.]
Eigen vectors

[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]


In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[9. 5.]

Eigenvectors:
[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]


In [ ]:
sorted_indices = np.argsort(np.abs(eigenvalues))[::-1]
sorted_eigenvalues = eigenvalues[sorted_indices]
sorted_eigenvectors = eigenvectors[:, sorted_indices]

print("Sorted Eigenvalues:")
print(sorted_eigenvalues)

print("\nSorted Eigenvectors:")
print(sorted_eigenvectors)

Sorted Eigenvalues:
[9. 5.]

Sorted Eigenvectors:
[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]


In [ ]:
k = 1
selected_eigenvectors = sorted_eigenvectors[:, :k]

print("Selected Eigenvectors:")
print(selected_eigenvectors)

Selected Eigenvectors:
[[0.89442719]
 [0.4472136 ]]


In [ ]:
projected_data = np.dot(deviations_matrix, eigenvectors)

print("Projected Data Points:")
print(projected_data)

Projected Data Points:
[[-3.57770876e+00 -2.57076777e-16]
 [-1.34164079e+00  2.23606798e+00]
 [-1.34164079e+00 -2.23606798e+00]
 [ 3.13049517e+00  2.23606798e+00]
 [ 3.13049517e+00 -2.23606798e+00]]


In [ ]:
projected_data = np.dot(deviations_matrix, eigenvectors)

print("Projected Data Points:")
print(projected_data)

Projected Data Points:
[[-3.57770876e+00 -2.57076777e-16]
 [-1.34164079e+00  2.23606798e+00]
 [-1.34164079e+00 -2.23606798e+00]
 [ 3.13049517e+00  2.23606798e+00]
 [ 3.13049517e+00 -2.23606798e+00]]
