<a href="https://colab.research.google.com/github/pujitha014/MACHINE_LEARNING/blob/main/python_basic_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)

1.23.5


In [ ]:
arr=np.array([2,3,4])
print(arr)
type(arr)

[2 3 4]


numpy.ndarray

In [ ]:
np.ones((2,2), dtype = float)
#to create the matrix

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.full((2,2),23)
#here we can give the user defined values

array([[23, 23],
       [23, 23]])

In [ ]:
np.arange(0,500,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255,
       260, 265, 270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320,
       325, 330, 335, 340, 345, 350, 355, 360, 365, 370, 375, 380, 385,
       390, 395, 400, 405, 410, 415, 420, 425, 430, 435, 440, 445, 450,
       455, 460, 465, 470, 475, 480, 485, 490, 495])

In [ ]:
np.linspace(0,500,5)

array([  0., 125., 250., 375., 500.])

In [ ]:
np.eye(4)
#to print the identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.random((3,3))

array([[0.94280255, 0.84650574, 0.90550441],
       [0.59776486, 0.06194739, 0.13709876],
       [0.31791519, 0.52514348, 0.21322064]])

In [ ]:
np.random.normal(5,10,(3,3))

array([[16.8861162 ,  2.50493295, -6.07527157],
       [12.54168969, 26.18803617,  7.09358368],
       [20.42927315,  0.57455744,  2.50188762]])

In [ ]:
np.random.randint(0, 10, (2,2))

array([[3, 7],
       [1, 6]])

In [ ]:
import numpy as np
np.random.seed(0)
x1 = np.random.randint(10, size = 5)
x2 = np.random.randint(10, size = (3,3))
x3 = np.random.randint(10, size = (3,4,5))
print("x3 ndim: ", x3.ndim)#this gives the dimensions(1D,2D,3D)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("dtype: ",x3.dtype)
print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes: ", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
dtype:  int64
x3 itemsize: 8 bytes
x3 nbytes:  480 bytes


In [ ]:
arr=np.array([1,3,5])
arr.dtype

dtype('int64')

In [ ]:
c = np.array([1, 2, 3])
c.dtype

dtype('int64')

In [ ]:
c=np.ones((3,3))
c.dtype

dtype('float64')

In [ ]:
x1 = np.random.randint(10, size = 5)
x1

array([3, 7, 5, 5, 0])

In [ ]:
x2 = np.random.randint(10, size = (3,3))
x2
x2[2, -1]

9

In [ ]:
x = np.arange(1, 10).reshape((3,3))
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x = np.array([1,2,3])
x.reshape([1, 3])
x.reshape((3, 1))
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [ ]:
x = np.array([3,4,5])
y = np.array([6,7,8])
np.concatenate([x, y])

array([3, 4, 5, 6, 7, 8])

In [ ]:
a = np.array([[1,2,3],
[4,5,6]])
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([a,a], axis = 1) #to

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
z = np.array([[22],
[25]])
np.hstack([y,z])

array([[ 8,  7,  6, 22],
       [ 5,  6,  4, 25]])

In [ ]:
x = [1, 2, 3, 22, 35, 6, 7, 8]
x1, x2, x3 = np.split(x, [3, 5])

In [ ]:
x = np.array([1,2,3])
y = np.array([[8,7,6],
[5,6,4]])
np.vstack([x,y])

array([[1, 2, 3],
       [8, 7, 6],
       [5, 6, 4]])